export const hotelTypes = [
  "Hotel",
  "Apartment",
  "Resort",
  "Villa",
  "Cabin",
  "Luxury",
  "Boutique",
  "Ski Lodge",
  "Beach Resort",
  "Golf Resort",
  "Motel",
  "Hostel",
  "Guesthouse",
  "Bed and Breakfast",
  "Farm Stay",
  "Ryokan",
  "Chalet",
  "Cottage",
  "Serviced Apartment",
  "Pet-friendly",
];